# Frozen regression baseline: named testsets that must remain green across remediation.
const BASELINE_TESTSETS = (
    "typed biological network",
    "positive production-destruction UDE",
    "augmented lagrangian mechanics",
    "augmented lagrangian end-to-end training",
    "deterministic resume equivalence",
    "augmented lagrangian resume equivalence",
    "implicit rational recovery",
    "Hill and competitive inhibition recovery",
    "graph-local basis scales with indegree",
    "experiment contracts",
    "execution backends and generated replicates",
    "versioned checkpoint",
    "compiler kinetic families",
    "general pipeline second topology",
    "type stability and allocation gates",
    "scientific release qualification",
    "multi-topology E2E",
    "README SciML ODE snippet",
    "SciMLBase ODEProblem contract",
    "SciML forward and adjoint contracts",
    "build_ude_function and SciML solve",
    "typed kinetic metadata",
    "typed metadata compiles p53 network",
    "dict metadata backward compatibility",
    "explicit STLSQ discovery backend",
    "Fisher identifiability report",
    "training retcode and gradient diagnostics",
    "discovery uncertainty reports",
    "multi-trajectory discovery",
    "scientific benchmark suite",
    "ground truth generator separation",
    "known linear parameter recovery",
    "known Michaelis–Menten parameter recovery",
    "graph-local vs global library ablation",
    "3-state graph prior vs global distractors",
    "6-state graph prior vs global distractors",
    "6-state wrong-graph negative control misses the true parent",
    "k_prod vs D practical identifiability is reported",
    "partial observation mask and subsampled Hill parent",
    "competitive unknown edge is 2D D(S,I) and keeps true parents",
    "Elowitz repressilator is a synthetic literature fixture",
    "Occam prune recovers sparse Hill on noisy rate samples",
    "CSV experiment roundtrip",
    "golden path export_rhs resimulation",
    "locked UDE KPI names",
    "production-destruction positivity invariant",
    "graph-local library excludes distractor Z",
    "discovery retcode messages",
    "ude_rhs! vs ude_system parity",
    "analytical Hill discovery breaks at σ = 0.05",
    "golden-path example smoke",
)

@testset "baseline gate" begin
    @test !isempty(BASELINE_TESTSETS)
    @test all(!isempty, BASELINE_TESTSETS)
end
