# Test-side helpers that were package internals up to 0.11: source-reading
# checks, consistency matrices, and the fixture rows they build on. They are
# loaded into the test process after `using BioDynaX` and use the package
# internals imported below (generated from the identifiers the helpers use).
using BioDynaX
import BioDynaX: BacksolveAdjoint, CHECKPOINT_SCHEMA_VERSION,
                 COMPILER_REINDEX_MUST_CONTAIN, COMPILER_REINDEX_MUST_NOT_CONTAIN,
                 Checkpoint,
                 ComponentVector, CustomDestructionTerm, MersenneTwister, ODEProblem,
                 REFERENCE_PROTOCOL_EXAMPLE_MUST_CONTAIN,
                 REFERENCE_PROTOCOL_EXAMPLE_MUST_NOT_CONTAIN,
                 REFERENCE_PROTOCOL_F1_ATTEMPT_MUST_CONTAIN,
                 REFERENCE_PROTOCOL_F1_ATTEMPT_MUST_NOT_CONTAIN, Random, SciMLBase,
                 Training,
                 TrainingSolveSession, Tsit5, _check_denominator_safety,
                 _denominator_domain_grid,
                 _destruction_contribution, _discover_explicit, _discover_implicit,
                 _discovery_retcode, _format_protocol_extras, _restore_frozen_phys,
                 _run_discovery,
                 _zero_frozen_phys_gradient, admit_recovery_suite_network,
                 assess_identifiability,
                 build_competitive_test_network, build_dual_unknown_network,
                 build_hill_recovery_network, build_linear_test_network,
                 build_mm_recovery_network,
                 build_remapped_two_regulator_network, build_six_state_unknown_network,
                 build_skipped_duplicate_unknown_network,
                 build_two_regulator_unknown_network,
                 build_zero_unknown_linear_network, coefficients_are_biological_constants,
                 compile_mechanism_source_path, compile_network,
                 compose_does_not_compile_row,
                 constant_rate_changes_residual_row, count_unknown_destructions,
                 denominator_domain_fixture_names, denominator_split_counts,
                 denominator_violation_count, deserialize, discover_then_compose_row,
                 discovery_jl_source_path, discovery_jl_source_path_for_denominator,
                 dual_only_throws_row, dual_per_term_compose_row, empty_export_rhs_row,
                 equation_to_function_explicit_row, evaluate_recovery, experiment_batches,
                 experiment_checkpoint_row_index, experiment_fingerprint,
                 experiment_jl_source_path,
                 experiment_set_is_compiled_once, extras_print_is_hardcoded_attempt,
                 extras_print_label, failed_compose_dual_only_row,
                 failed_compose_empty_export_row,
                 failed_compose_empty_terms_row, failed_compose_export_row,
                 failed_compose_linear_term_row, failed_compose_wrong_rate_row,
                 failed_export_rhs_row, failed_solve_residual_is_inf_row,
                 failure_mode_row_index,
                 format_denominator_domain_index, format_experiment_checkpoint_index,
                 format_failure_mode_index, format_graph_local_library_index,
                 format_hybrid_compose_index, format_hybrid_residual_index,
                 format_identifiability_product_index, format_parameter_schema_pack_index,
                 format_production_destruction_warning, format_protocol_result,
                 format_suite_library_index, frozen_phys_warmup_report,
                 graph_local_library_fixture_names, grid,
                 hill_known_generate_unknown_identity_row,
                 hill_known_generate_unknown_solver_row, horizon_curriculum_session_report,
                 hybrid_compose_fixture_names, hybrid_compose_identity_matrix,
                 hybrid_compose_typed_matrix, hybrid_linear_unknown_model,
                 hybrid_residual_failed_solve_row, hybrid_residual_fixture_names,
                 hybrid_residual_identity_matrix, hybrid_residual_model_solve,
                 hybrid_residual_sciml_solve, hybrid_residual_shape_guard_row,
                 hybrid_residual_source_path, hybrid_residual_typed_matrix,
                 ident_interventions_does_not_train_unknown_edge_source,
                 identifiability_jl_source_path, identifiability_product_fixture_names,
                 init,
                 inneighbors, inverse_softplus, irregular_times_residual_row,
                 kinetic_known_no_compose_row, kinetic_known_no_residual_row,
                 linear_training_fixture, linear_zero_hole_compose_row,
                 linear_zero_hole_residual_row, load_checkpoint,
                 local_has_false_parent_check,
                 local_has_true_parent_check, lock_training_solver,
                 masked_experiment_compile_report,
                 mean, middle, mm_known_no_compose_row, mm_known_no_residual_row,
                 multi_ic_identity_residual_row, multi_ic_residual_solver_row, network,
                 neural_head_count, neural_index_is_dense,
                 neural_training_requires_interpolating,
                 noise_does_not_paint_f1_row, noise_grid_residual_row,
                 normalize_destruction_samples,
                 only_unknown_destruction, optimizer_state_roundtrip_report,
                 parameter_schema_jl_source_path, parameter_schema_pack_fixture_names,
                 partial_obs_does_not_train_unknown_edge_source, predict_ude_session,
                 production_destruction_tradeoff, protocol_fingerprint_not_dropped_row,
                 recommend_sensealg, recovery_jl_source_path,
                 recovery_jl_source_path_for_denominator,
                 recovery_suite_all_sections_checked,
                 recovery_suite_default_sections_source,
                 recovery_suite_reference_protocol_sections,
                 recovery_suite_reference_protocol_trainers,
                 reference_protocol_example_path,
                 reference_protocol_experiment_set, reference_protocol_f1_attempt_path,
                 reference_protocol_f1_attempt_spec, reference_protocol_recovery_admits,
                 reference_protocol_smoke_identity_row, reference_protocol_training_config,
                 remake,
                 remapped_compose_row, remapped_residual_solver_row,
                 repressilator_no_compose_row,
                 repressilator_no_residual_row, residual_shape_guard_row,
                 resume_from_diagnostics_report, rng,
                 sample_destruction_matches_identity_row,
                 save_checkpoint, sensealg, serialize, session_predict_hybrid_row,
                 session_residual_solver_path, shuffle, shuffle!,
                 skipped_duplicate_compose_row,
                 skipped_duplicate_residual_solver_row, skipped_middle_compose_row,
                 skipped_middle_residual_solver_row, skipped_section_does_not_admit_source,
                 skipped_section_does_not_generate_set_source, smoke_identity_on_self_row,
                 smoke_vs_protocol_residual_row, solve, support_uses_variable,
                 train_ude_compile_report,
                 train_unknown_edge_only_in_reference_protocol_source,
                 training_jl_checkpoint_source, training_jl_source_path,
                 training_sensealg_is_locked,
                 training_sensealg_kind, training_session_matches_generate,
                 training_session_multi_ic_agreement, training_session_remake_agreement,
                 ude_extras_denominator_row, ude_jl_source_path_for_pack, unpack_parameters,
                 warmup_first_experiment, with_compile_network_counter
include("source_checks.jl")
