@setup_workload begin
    network = build_linear_test_network()
    rng = MersenneTwister(0)
    @compile_workload begin
        validate_network(network)
        state_nodes(network)
        compile_mechanism(network)
        local_basis(network, 1; degree = 2)
        model, params = build_ude_model(rng, network)
        u = [0.2, 0.1]
        ude_system(u, params, 0.0, model)
        cache = allocate_cache(model, Float64)
        ude_rhs!(cache.du, u, params, 0.0, model, cache)
        SciMLBase.ODEProblem(model, u, (0.0, 1.0), params)
        unique_claim_fingerprint()
        unique_claim_fingerprint(; smoke = true)
        neural_index_is_dense(compile_mechanism(network))
        extras_print_label(nothing)
        extras_print_label(String[])
        admit_recovery_suite_network(:linear)
        recovery_suite_section_kind(:ude_discovery)
        format_unique_claim_kpi_failures(Symbol[])
        compile_ground_truth_model(rng, network)
        extras_print_label(("1", "r"))
        recovery_suite_hole_policy(:ude_discovery)
        recovery_suite_expected_holes(:linear)
        allocate_stlsq_workspace(Float64, 16, 4, 8)
        _backend_chunk_size(ImplicitSINDyPI(chunk_size = 32))
        lock_training_solver(model)
        training_solve_session(model, u, (0.0, 1.0), params)
    end
end
